# Generated by Django 4.0.6 on 2023-07-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateTimeField(auto_now_add=True, verbose_name='дата и время запуска рассылки')),
                ('textMassage', models.TextField(verbose_name='текст сообщения для доставки клиенту')),
                ('filterClientCodeOperator', models.IntegerField(blank=True, null=True, verbose_name='фильтр клиентов по коду оператора')),
                ('filterClientTag', models.CharField(blank=True, max_length=150, null=True, verbose_name='фильтр клиентов по тэгу')),
                ('dateFinish', models.DateTimeField(verbose_name='дата и время окончания рассылки')),
            ],
            options={
                'verbose_name': 'рассылки',
            },
        ),
    ]
