# Generated by Django 4.0.6 on 2023-07-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberPhone', models.IntegerField(max_length=11, verbose_name='номер телефона клиента')),
                ('codeOperator', models.CharField(max_length=150, verbose_name='код мобильного оператора')),
                ('tag', models.CharField(max_length=50, verbose_name='тег (произвольная метка)')),
                ('timeZone', models.CharField(max_length=100, verbose_name='часовой пояс')),
            ],
            options={
                'verbose_name': 'клиенты',
            },
        ),
        migrations.AlterField(
            model_name='mailinglistmodel',
            name='filterClientCodeOperator',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='фильтр клиентов по коду оператора'),
        ),
    ]
