# Generated by Django 4.0.6 on 2023-07-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_clientmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistmodel',
            name='filterClientTag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='фильтр клиентов по тэгу'),
        ),
    ]
