# Generated by Django 4.0.6 on 2023-07-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_mailinglistmodel_filterclienttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreate', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания (отправки)')),
                ('status', models.CharField(max_length=50, verbose_name='статус отправки')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.clientmodel', verbose_name='id клиента, которому отправили')),
                ('MailingList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.mailinglistmodel', verbose_name='id рассылки, в рамках которой было отправлено сообщение')),
            ],
            options={
                'verbose_name': 'сообщения',
            },
        ),
    ]
